name: cross_connectivity
version: 4.0.5
homepage: https://github.com/marchdev-tk/cross_connectivity
description: A Flutter plugin for handling Connectivity and REAL Connection state in the mobile, web and desktop platforms. Supports iOS, Android, Web, Windows, Linux and macOS.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0
  http: ^1.1.0
  rxdart: ^0.27.3
  connectivity_plus: ^2.2.1
  connectivity_plus_linux: ^1.3.0
  connectivity_plus_macos: ^1.2.1
  connectivity_plus_windows: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
